volumes:
  pgadmin-vol:

services:
  pgadmin:
    image: dpage/pgadmin4:6.19
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_PASSWORD: pwd
      PGADMIN_DEFAULT_EMAIL: yacine.touati.pro@gmail.com
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8081:8080
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
